version: "3.9"

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api
      - bot
    environment:
      DOMAIN: ${DOMAIN}
      PUBLIC_BASE: ${PUBLIC_BASE}
      WEBAPP_ORIGIN: ${WEBAPP_ORIGIN}

  api:
    build: ./api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WEBAPP_ORIGIN: ${WEBAPP_ORIGIN}
    expose:
      - "8000"

  bot:
    build: ./bot
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      API_BASE: https://${DOMAIN}/api
    expose:
      - "8081"

